"""Alternative Proposal Generation (v0.5.3 / Phase 5.5).

If the system only knows "A failed → avoid A" but doesn't know what to
try INSTEAD, it cannot truly learn.  Alternative Proposal Generation
creates K candidate modifications and selects the best one based on
experience.

Each round generates:
    A_t = {a_1, a_2, ..., a_K}

Score each candidate:
    Score(a_i) = f(state, error, memory, experience_value)

Select:
    a* = argmax Score(a_i)   (with exploration)

The candidates include:
    1. Base proposal (from plasticity module)
    2. Target switch (different parameter group)
    3. Magnitude perturbation (larger/smaller)
    4. Direction perturbation (orthogonal perturbation)

This replaces the v0.5.2 approach where only ONE proposal was generated
and there was no mechanism to try alternatives.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np


@dataclass
class ModificationCandidate:
    """One candidate modification."""
    candidate_id: int = 0
    target_group: int = 0
    magnitude: float = 0.05
    direction_perturbation: Optional[Any] = None  # (32,) perturbation vector
    score: float = 0.0
    selected: bool = False
    # tracking
    experience_id: str = ""            # linked experience that inspired this
    outcome: str = "unknown"           # unknown until executed
    future_value: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "candidate_id": self.candidate_id,
            "target_group": self.target_group,
            "magnitude": self.magnitude,
            "score": self.score,
            "selected": self.selected,
            "experience_id": self.experience_id,
            "outcome": self.outcome,
        }


class AlternativeProposalGenerator:
    """Generate K candidate modifications and select the best.

    This is a MODEL-SIDE mechanism (not rule-based):
    1. K candidates are generated by the policy network
    2. Each candidate is scored by the policy
    3. Selection uses ε-greedy over the scored candidates
    4. Selected candidate's outcome is tracked

    Design constraints (task spec §19-23):
    - Candidates must be generated by the model, not hard-coded rules
    - Randomness is for exploration between candidates, not random mods
    - Each candidate tracks its own outcome for learning
    - Data leakage prevention: unexecuted candidates have outcome=unknown
    """

    def __init__(self, n_candidates: int = 4,
                 n_target_groups: int = 3,
                 m_min: float = 0.02, m_max: float = 1.0,
                 exploration_eps: float = 0.15,
                 exploration_min: float = 0.02,
                 exploration_decay: float = 0.001):
        self.n_candidates = n_candidates
        self.n_target_groups = n_target_groups
        self.m_min = m_min
        self.m_max = m_max
        self.exploration_eps = exploration_eps
        self.exploration_min = exploration_min
        self.exploration_decay = exploration_decay

        # candidate history
        self.history: List[Dict[str, Any]] = []
        self.total_generated = 0
        self.total_selected = 0

    def generate_candidates(
        self,
        base_target: int,
        base_magnitude: float,
        candidate_scores: Optional[torch.Tensor] = None,
        magnitude_values: Optional[torch.Tensor] = None,
        direction_mod: Optional[torch.Tensor] = None,
    ) -> List[ModificationCandidate]:
        """Generate K candidate modifications.

        Strategy:
        1. Candidate 0: base proposal (as-is)
        2. Candidate 1: switch target to next group
        3. Candidate 2: perturb magnitude (±30%)
        4. Candidate 3: switch target to third group

        If candidate_scores is provided, use it to override scores.

        Args:
            base_target: target group from base policy.
            base_magnitude: magnitude from base policy.
            candidate_scores: (K,) raw scores from policy.
            magnitude_values: (K,) magnitudes for each candidate.
            direction_mod: (K, 32) direction modulations.

        Returns:
            List of K ModificationCandidate objects.
        """
        candidates = []
        for i in range(self.n_candidates):
            if i == 0:
                # base proposal
                target = base_target
                mag = base_magnitude
            elif i == 1:
                # target switch: cycle to next group
                target = (base_target + 1) % self.n_target_groups
                mag = base_magnitude
            elif i == 2:
                # magnitude perturbation
                target = base_target
                mag = float(np.clip(
                    base_magnitude * np.random.uniform(0.5, 2.0),
                    self.m_min, self.m_max))
            elif i == 3:
                # target switch to third group
                target = (base_target + 2) % self.n_target_groups
                mag = base_magnitude
            else:
                # additional: random target + random magnitude
                target = np.random.randint(0, self.n_target_groups)
                mag = float(np.random.uniform(self.m_min, self.m_max))

            # override score if provided
            score = 0.0
            if candidate_scores is not None and i < candidate_scores.size(-1):
                score = float(candidate_scores[0, i].item()) \
                    if candidate_scores.dim() > 1 else float(candidate_scores[i].item())

            candidates.append(ModificationCandidate(
                candidate_id=i,
                target_group=target,
                magnitude=mag,
                score=score,
            ))

        self.total_generated += len(candidates)
        return candidates

    def select_candidate(
        self,
        candidates: List[ModificationCandidate],
        exploration_eps: Optional[float] = None,
    ) -> ModificationCandidate:
        """Select a candidate using ε-greedy over scores.

        Args:
            candidates: K candidates with scores.
            exploration_eps: override exploration rate.

        Returns:
            The selected ModificationCandidate.
        """
        eps = exploration_eps if exploration_eps is not None else self.exploration_eps
        eps = max(eps, self.exploration_min)

        if np.random.random() < eps:
            # exploration: random selection
            selected = np.random.choice(len(candidates))
        else:
            # exploitation: best score
            scores = [c.score for c in candidates]
            selected = int(np.argmax(scores))

        candidates[selected].selected = True
        self.total_selected += 1

        # decay exploration
        self.exploration_eps = max(
            self.exploration_min,
            self.exploration_eps - self.exploration_decay)

        return candidates[selected]

    def record_outcome(self, candidate: ModificationCandidate,
                       outcome: str) -> None:
        """Record the outcome of a selected candidate.

        IMPORTANT: only the SELECTED candidate gets an outcome.
        Unexecuted candidates have outcome="unknown" (no data leakage).
        """
        candidate.outcome = outcome
        self.history.append({
            "candidate_id": candidate.candidate_id,
            "target_group": candidate.target_group,
            "magnitude": candidate.magnitude,
            "score": candidate.score,
            "outcome": outcome,
        })

    def candidate_outcome_rate(self, outcome: str = "success") -> float:
        """Fraction of selected candidates with given outcome."""
        executed = [h for h in self.history if h["outcome"] != "unknown"]
        if not executed:
            return 0.0
        matching = sum(1 for h in executed if h["outcome"] == outcome)
        return matching / len(executed)

    def target_distribution(self) -> Dict[int, float]:
        """Distribution of selected targets over history."""
        if not self.history:
            return {}
        counts: Dict[int, int] = {}
        for h in self.history:
            t = h["target_group"]
            counts[t] = counts.get(t, 0) + 1
        total = len(self.history)
        return {t: c / total for t, c in counts.items()}

    def magnitude_distribution(self) -> Dict[str, float]:
        """Statistics of selected magnitudes."""
        if not self.history:
            return {"mean": 0.0, "std": 0.0}
        mags = [h["magnitude"] for h in self.history]
        arr = np.array(mags)
        return {"mean": float(arr.mean()), "std": float(arr.std()),
                "min": float(arr.min()), "max": float(arr.max())}

    def summary(self) -> Dict[str, Any]:
        return {
            "n_generated": self.total_generated,
            "n_selected": self.total_selected,
            "n_outcomes": len(self.history),
            "success_rate": self.candidate_outcome_rate("success"),
            "failure_rate": self.candidate_outcome_rate("failure"),
            "target_distribution": self.target_distribution(),
            "magnitude_distribution": self.magnitude_distribution(),
            "exploration_rate": self.exploration_eps,
        }

    def to_dict(self) -> Dict[str, Any]:
        return self.summary()
